import Link from 'next/link'

const features = [
  {
    emoji: '🧮',
    title: 'Calorie Calculator',
    desc: 'Enter your age, weight, height, and activity level. We calculate your exact daily calorie target using the Mifflin-St Jeor formula.',
    badge: 'Free',
  },
  {
    emoji: '📋',
    title: 'Daily Food Log',
    desc: 'Log every meal in seconds. Track breakfast, lunch, dinner, and snacks. Watch your progress bar fill up through the day.',
    badge: 'Free',
  },
  {
    emoji: '✨',
    title: 'AI Meal Plans',
    desc: 'Get a personalised 7-day meal plan generated by Claude AI, tailored to your calorie target and whether you want to lose, maintain, or gain weight.',
    badge: 'Pro',
  },
]

const pricingFree = [
  'TDEE & BMR calculator',
  'Daily food log',
  'Calorie progress tracking',
  'Breakfast, lunch, dinner & snacks',
]

const pricingPro = [
  'Everything in Free',
  'AI-generated 7-day meal plan',
  'Personalised to your goal',
  'Daily macro breakdown',
  'Unlimited plan history',
]

export default function LandingPage() {
  return (
    <div className="min-h-screen bg-white">

      {/* Nav */}
      <header className="border-b border-gray-100">
        <div className="max-w-5xl mx-auto px-4 h-14 flex items-center justify-between">
          <span className="text-lg font-bold text-green-600">CalorieApp</span>
          <div className="flex items-center gap-3">
            <Link href="/login" className="text-sm text-gray-600 hover:text-gray-900 font-medium">
              Sign in
            </Link>
            <Link
              href="/register"
              className="text-sm bg-green-600 text-white px-4 py-1.5 rounded-lg font-medium hover:bg-green-700 transition-colors"
            >
              Get started free
            </Link>
          </div>
        </div>
      </header>

      {/* Hero */}
      <section className="max-w-5xl mx-auto px-4 pt-20 pb-16 text-center">
        <span className="inline-block bg-green-50 text-green-700 text-sm font-medium px-3 py-1 rounded-full mb-6">
          Free to start · No credit card needed
        </span>
        <h1 className="text-5xl font-extrabold text-gray-900 leading-tight mb-5">
          Track calories.<br />Reach your goal.
        </h1>
        <p className="text-xl text-gray-500 max-w-xl mx-auto mb-8">
          Calculate your daily calorie target, log your meals, and get an AI-generated meal plan personalised to your goal.
        </p>
        <div className="flex items-center justify-center gap-3">
          <Link
            href="/register"
            className="bg-green-600 text-white px-6 py-3 rounded-xl font-semibold text-lg hover:bg-green-700 transition-colors"
          >
            Start for free
          </Link>
          <Link
            href="#pricing"
            className="text-gray-600 px-6 py-3 rounded-xl font-semibold text-lg border border-gray-200 hover:border-gray-300 transition-colors"
          >
            See pricing
          </Link>
        </div>
      </section>

      {/* Features */}
      <section className="bg-gray-50 py-16">
        <div className="max-w-5xl mx-auto px-4">
          <h2 className="text-2xl font-bold text-gray-900 text-center mb-10">
            Everything you need to hit your goal
          </h2>
          <div className="grid md:grid-cols-3 gap-6">
            {features.map(f => (
              <div key={f.title} className="bg-white rounded-2xl p-6 shadow-sm border border-gray-100">
                <div className="text-3xl mb-3">{f.emoji}</div>
                <div className="flex items-center gap-2 mb-2">
                  <h3 className="font-bold text-gray-900">{f.title}</h3>
                  <span className={`text-xs px-2 py-0.5 rounded-full font-medium ${
                    f.badge === 'Pro'
                      ? 'bg-green-100 text-green-700'
                      : 'bg-gray-100 text-gray-500'
                  }`}>
                    {f.badge}
                  </span>
                </div>
                <p className="text-gray-500 text-sm leading-relaxed">{f.desc}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Pricing */}
      <section id="pricing" className="py-16">
        <div className="max-w-3xl mx-auto px-4">
          <h2 className="text-2xl font-bold text-gray-900 text-center mb-3">Simple pricing</h2>
          <p className="text-gray-500 text-center mb-10">Start free. Upgrade when you&apos;re ready.</p>

          <div className="grid md:grid-cols-2 gap-6">

            {/* Free */}
            <div className="bg-white rounded-2xl border border-gray-200 p-7">
              <h3 className="text-lg font-bold text-gray-900 mb-1">Free</h3>
              <div className="text-3xl font-bold text-gray-900 mb-1">$0</div>
              <p className="text-sm text-gray-400 mb-6">Forever free</p>
              <ul className="space-y-3 mb-8">
                {pricingFree.map(f => (
                  <li key={f} className="flex items-center gap-3 text-sm text-gray-600">
                    <span className="text-green-500 font-bold">✓</span> {f}
                  </li>
                ))}
              </ul>
              <Link
                href="/register"
                className="block w-full text-center border border-gray-300 text-gray-700 py-2.5 rounded-xl font-semibold hover:border-gray-400 transition-colors"
              >
                Get started
              </Link>
            </div>

            {/* Pro */}
            <div className="bg-green-600 rounded-2xl p-7 text-white">
              <h3 className="text-lg font-bold mb-1">Pro</h3>
              <div className="text-3xl font-bold mb-1">$9</div>
              <p className="text-sm text-green-200 mb-6">per month · cancel anytime</p>
              <ul className="space-y-3 mb-8">
                {pricingPro.map(f => (
                  <li key={f} className="flex items-center gap-3 text-sm text-green-50">
                    <span className="text-white font-bold">✓</span> {f}
                  </li>
                ))}
              </ul>
              <Link
                href="/register"
                className="block w-full text-center bg-white text-green-700 py-2.5 rounded-xl font-semibold hover:bg-green-50 transition-colors"
              >
                Start free → upgrade inside
              </Link>
            </div>

          </div>
        </div>
      </section>

      {/* Footer CTA */}
      <section className="bg-gray-50 py-16 text-center">
        <h2 className="text-2xl font-bold text-gray-900 mb-3">Ready to start?</h2>
        <p className="text-gray-500 mb-6">Create your free account in 30 seconds.</p>
        <Link
          href="/register"
          className="inline-block bg-green-600 text-white px-8 py-3 rounded-xl font-semibold text-lg hover:bg-green-700 transition-colors"
        >
          Create free account
        </Link>
      </section>

      {/* Footer */}
      <footer className="border-t border-gray-100 py-6 text-center text-sm text-gray-400">
        © {new Date().getFullYear()} CalorieApp · Built with Next.js
      </footer>

    </div>
  )
}
