import Link from 'next/link'

const features = [
  {
    emoji: '🧮',
    title: 'Calorie Calculator',
    desc: 'Enter your age, weight, height, and activity level. We calculate your exact daily calorie target using the Mifflin-St Jeor formula.',
    badge: 'Free',
  },
  {
    emoji: '📋',
    title: 'Daily Food Log',
    desc: 'Log every meal in seconds. Track breakfast, lunch, dinner, and snacks. Watch your progress bar fill up through the day.',
    badge: 'Free',
  },
  {
    emoji: '✨',
    title: 'AI Meal Plans',
    desc: 'Get a personalised 7-day meal plan generated by Claude AI, tailored to your calorie target and whether you want to lose, maintain, or gain weight.',
    badge: 'Pro',
  },
]

const testimonials = [
  {
    avatar: '👩',
    name: 'Sarah M.',
    tag: 'Lost 8 kg in 3 months',
    quote: "I've tried so many apps but this one actually stuck. The food search has all the Malaysian food I eat daily — nasi lemak, roti canai, everything. Finally an app that gets it.",
  },
  {
    avatar: '👨',
    name: 'James L.',
    tag: 'Maintaining weight',
    quote: "The calorie calculator was eye-opening. I had no idea how much I was eating. Two weeks in and I finally feel in control — the progress bar every day keeps me honest.",
  },
  {
    avatar: '👩‍💼',
    name: 'Priya K.',
    tag: 'Pro subscriber',
    quote: "The AI meal plan is genuinely impressive. A full week of meals tailored to my calorie target — I just follow it and it works. Worth every cent of the Pro plan.",
  },
]

const pricingFree = [
  'TDEE & BMR calculator',
  'Daily food log',
  'Calorie progress tracking',
  'Breakfast, lunch, dinner & snacks',
  '7-day calorie chart',
  'Water tracking',
]

const pricingPro = [
  'Everything in Free',
  'AI-generated 7-day meal plan',
  'Personalised to your goal',
  'Daily macro breakdown',
  'Unlimited plan history',
]

const heroFruits = [
  { emoji: '🍎', top: '12%',  left: '6%',   size: '3.2rem', dur: 4.2, delay: 0   },
  { emoji: '🥑', top: '22%',  left: '88%',  size: '2.8rem', dur: 5.0, delay: 0.6 },
  { emoji: '🍊', top: '62%',  left: '5%',   size: '2.4rem', dur: 6.1, delay: 1.2 },
  { emoji: '🫐', top: '70%',  left: '91%',  size: '3rem',   dur: 4.7, delay: 0.3 },
  { emoji: '🥦', top: '40%',  left: '3%',   size: '2.2rem', dur: 5.5, delay: 1.8 },
  { emoji: '🍋', top: '18%',  left: '78%',  size: '2.4rem', dur: 4.0, delay: 2.0 },
  { emoji: '🍇', top: '78%',  left: '12%',  size: '2.8rem', dur: 5.3, delay: 1.0 },
  { emoji: '🍓', top: '30%',  left: '93%',  size: '2.2rem', dur: 6.0, delay: 0.5 },
  { emoji: '🥕', top: '82%',  left: '82%',  size: '2.4rem', dur: 4.5, delay: 2.4 },
  { emoji: '🍌', top: '50%',  left: '96%',  size: '2.8rem', dur: 5.8, delay: 1.5 },
  { emoji: '🍒', top: '55%',  left: '1%',   size: '2rem',   dur: 4.3, delay: 0.9 },
  { emoji: '🍍', top: '8%',   left: '50%',  size: '2rem',   dur: 5.2, delay: 3.0 },
  { emoji: '🥝', top: '44%',  left: '92%',  size: '2.2rem', dur: 4.8, delay: 2.1 },
]

export default function LandingPage() {
  return (
    <div className="min-h-screen">

      {/* Nav */}
      <header className="bg-white/70 backdrop-blur-sm border-b border-white/60 sticky top-0 z-10">
        <div className="max-w-5xl mx-auto px-4 h-14 flex items-center justify-between">
          <span className="text-lg font-bold text-green-600">CalorieApp</span>
          <div className="flex items-center gap-3">
            <Link href="/login" className="text-sm text-gray-600 hover:text-gray-900 font-medium">
              Sign in
            </Link>
            <Link
              href="/register"
              className="text-sm bg-green-600 text-white px-4 py-1.5 rounded-lg font-medium hover:bg-green-700 transition-colors"
            >
              Get started free
            </Link>
          </div>
        </div>
      </header>

      {/* Hero */}
      <section className="relative overflow-hidden py-24 pb-20">
        {heroFruits.map((f, i) => (
          <span key={i} style={{
            position: 'absolute', top: f.top, left: f.left, fontSize: f.size,
            opacity: 0.22, userSelect: 'none', pointerEvents: 'none',
            animation: `float ${f.dur}s ease-in-out infinite`,
            animationDelay: `${f.delay}s`,
          }}>{f.emoji}</span>
        ))}
        <div className="relative z-10 max-w-5xl mx-auto px-4 text-center">
          <span className="inline-block bg-white/80 text-green-700 text-sm font-semibold px-4 py-1.5 rounded-full mb-6 border border-green-100 shadow-sm">
            🎉 Free to start · No credit card needed
          </span>
          <h1 className="text-6xl font-extrabold text-gray-900 leading-tight mb-5">
            Track calories.<br />
            <span style={{ background: 'linear-gradient(135deg, #16a34a, #f97316)', WebkitBackgroundClip: 'text', WebkitTextFillColor: 'transparent' }}>
              Reach your goal.
            </span>
          </h1>
          <p className="text-xl text-gray-600 max-w-xl mx-auto mb-10">
            Calculate your daily calorie target, log your meals, and get an AI-generated meal plan personalised to your goal.
          </p>
          <div className="flex items-center justify-center gap-4">
            <Link
              href="/register"
              className="bg-green-600 text-white px-8 py-4 rounded-2xl font-bold text-lg hover:bg-green-700 transition-all shadow-lg hover:shadow-xl hover:-translate-y-0.5"
            >
              Start for free →
            </Link>
            <Link
              href="#pricing"
              className="bg-white/80 text-gray-700 px-8 py-4 rounded-2xl font-bold text-lg border border-gray-200 hover:border-gray-300 transition-all shadow-sm"
            >
              See pricing
            </Link>
          </div>
        </div>
      </section>

      {/* Features */}
      <section className="py-16 bg-white/50">
        <div className="max-w-5xl mx-auto px-4">
          <h2 className="text-2xl font-bold text-gray-900 text-center mb-10">
            Everything you need to hit your goal
          </h2>
          <div className="grid md:grid-cols-3 gap-6">
            {features.map(f => (
              <div key={f.title} className="bg-white/80 rounded-2xl p-6 shadow-sm border border-white/60">
                <div className="text-3xl mb-3">{f.emoji}</div>
                <div className="flex items-center gap-2 mb-2">
                  <h3 className="font-bold text-gray-900">{f.title}</h3>
                  <span className={`text-xs px-2 py-0.5 rounded-full font-medium ${
                    f.badge === 'Pro'
                      ? 'bg-green-100 text-green-700'
                      : 'bg-gray-100 text-gray-500'
                  }`}>
                    {f.badge}
                  </span>
                </div>
                <p className="text-gray-500 text-sm leading-relaxed">{f.desc}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Testimonials */}
      <section className="py-16">
        <div className="max-w-5xl mx-auto px-4">
          <h2 className="text-2xl font-bold text-gray-900 text-center mb-2">
            People who&apos;ve made it work
          </h2>
          <p className="text-gray-500 text-center mb-10">Real results from real users.</p>
          <div className="grid md:grid-cols-3 gap-6">
            {testimonials.map(t => (
              <div key={t.name} className="bg-white/80 rounded-2xl p-6 shadow-sm border border-white/60 flex flex-col gap-4">
                <div className="flex gap-1">
                  {[...Array(5)].map((_, i) => (
                    <span key={i} className="text-yellow-400 text-sm">★</span>
                  ))}
                </div>
                <p className="text-gray-600 text-sm leading-relaxed flex-1">&ldquo;{t.quote}&rdquo;</p>
                <div className="flex items-center gap-3 pt-2 border-t border-gray-100">
                  <span className="text-2xl">{t.avatar}</span>
                  <div>
                    <p className="text-sm font-semibold text-gray-800">{t.name}</p>
                    <p className="text-xs text-green-600 font-medium">{t.tag}</p>
                  </div>
                </div>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Pricing */}
      <section id="pricing" className="py-16 bg-white/50">
        <div className="max-w-3xl mx-auto px-4">
          <h2 className="text-2xl font-bold text-gray-900 text-center mb-3">Simple pricing</h2>
          <p className="text-gray-500 text-center mb-10">Start free. Upgrade when you&apos;re ready.</p>

          <div className="grid md:grid-cols-2 gap-6">

            {/* Free */}
            <div className="bg-white/80 rounded-2xl border border-gray-200 p-7">
              <h3 className="text-lg font-bold text-gray-900 mb-1">Free</h3>
              <div className="text-3xl font-bold text-gray-900 mb-1">$0</div>
              <p className="text-sm text-gray-400 mb-6">Forever free</p>
              <ul className="space-y-3 mb-8">
                {pricingFree.map(f => (
                  <li key={f} className="flex items-center gap-3 text-sm text-gray-600">
                    <span className="text-green-500 font-bold">✓</span> {f}
                  </li>
                ))}
              </ul>
              <Link
                href="/register"
                className="block w-full text-center border border-gray-300 text-gray-700 py-2.5 rounded-xl font-semibold hover:border-gray-400 transition-colors"
              >
                Get started
              </Link>
            </div>

            {/* Pro */}
            <div className="bg-green-600 rounded-2xl p-7 text-white">
              <h3 className="text-lg font-bold mb-1">Pro</h3>
              <div className="text-3xl font-bold mb-1">$9</div>
              <p className="text-sm text-green-200 mb-6">per month · cancel anytime</p>
              <ul className="space-y-3 mb-8">
                {pricingPro.map(f => (
                  <li key={f} className="flex items-center gap-3 text-sm text-green-50">
                    <span className="text-white font-bold">✓</span> {f}
                  </li>
                ))}
              </ul>
              <Link
                href="/register"
                className="block w-full text-center bg-white text-green-700 py-2.5 rounded-xl font-semibold hover:bg-green-50 transition-colors"
              >
                Start free → upgrade inside
              </Link>
            </div>

          </div>
        </div>
      </section>

      {/* Footer CTA */}
      <section className="py-16 text-center">
        <h2 className="text-2xl font-bold text-gray-900 mb-3">Ready to start?</h2>
        <p className="text-gray-500 mb-6">Create your free account in 30 seconds.</p>
        <Link
          href="/register"
          className="inline-block bg-green-600 text-white px-8 py-3 rounded-xl font-semibold text-lg hover:bg-green-700 transition-colors shadow-lg"
        >
          Create free account
        </Link>
      </section>

      {/* Footer */}
      <footer className="border-t border-white/60 py-6 text-center text-sm text-gray-400 bg-white/40">
        © {new Date().getFullYear()} CalorieApp · Built with Next.js
      </footer>

    </div>
  )
}
