'use client'

import { useState } from 'react'

const features = [
  'AI-generated 7-day meal plan',
  'Personalised to your calorie goal',
  'Daily macros breakdown',
  'Unlimited plan history',
]

export default function UpgradeCTA({ showSuccess }: { showSuccess: boolean }) {
  const [loading, setLoading] = useState(false)
  const [error,   setError]   = useState('')

  async function handleUpgrade() {
    setLoading(true)
    setError('')
    const res = await fetch('/api/stripe/checkout', { method: 'POST' })
    const { url, error } = await res.json()
    if (url) {
      window.location.href = url
    } else {
      setError(error ?? 'Something went wrong. Please try again.')
      setLoading(false)
    }
  }

  return (
    <div className="max-w-md">
      {showSuccess && (
        <div className="mb-6 bg-green-50 border border-green-200 rounded-xl p-4 text-green-700 font-medium">
          🎉 Payment successful — you&apos;re now on Pro!
        </div>
      )}

      <h1 className="text-2xl font-bold text-gray-900 mb-1">AI Meal Plan</h1>
      <p className="text-gray-500 mb-8">
        Upgrade to Pro and get a personalised 7-day meal plan generated by AI.
      </p>

      <div className="bg-white rounded-2xl shadow-sm border border-gray-100 p-8">
        <div className="text-center mb-6">
          <div className="text-4xl mb-3">✨</div>
          <h2 className="text-xl font-bold text-gray-900">CalorieApp Pro</h2>
          <div className="mt-3 text-4xl font-bold text-gray-900">
            $9
            <span className="text-base font-normal text-gray-400"> / month</span>
          </div>
        </div>

        <ul className="space-y-3 mb-8">
          {features.map(f => (
            <li key={f} className="flex items-center gap-3 text-sm text-gray-600">
              <span className="text-green-500 font-bold">✓</span>
              {f}
            </li>
          ))}
        </ul>

        {error && <p className="text-sm text-red-600 mb-4">{error}</p>}

        <button
          onClick={handleUpgrade}
          disabled={loading}
          className="w-full bg-green-600 text-white py-3 rounded-xl font-semibold text-lg hover:bg-green-700 disabled:opacity-50 transition-colors"
        >
          {loading ? 'Redirecting to checkout…' : 'Upgrade to Pro →'}
        </button>
        <p className="text-xs text-center text-gray-400 mt-3">
          Powered by Stripe · Cancel anytime
        </p>
      </div>
    </div>
  )
}
